spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/simple-api
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:db/migration

